language: ruby
services:
  - docker

before_install:
  - docker pull coedl/elpis:interspeech-19

script:
  - ls
  - ls elpis
  - ls /
  - pwd
  - docker run --rm --entrypoint='' coedl/elpis:interspeech-19 sh -c "git pull origin cnc; git checkout -b cnc; pip install coveralls pytest-cov; py.test -v --cov=elpis --cov-report=term-missing; export GIT_BRANCH=cnc; export COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN; coveralls"

