language: ruby
services:
  - docker

before_install:
  - docker pull coedl/elpis:interspeech-19

script:
  - ls
  - pwd
  - docker run --rm --entrypoint='' coedl/elpis:interspeech-19 sh -c "git pull origin cnc; pip install python-coveralls pytest-cov; py.test -v --cov=coveralls --cov-report=term-missing; export COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN; coveralls"

