language: ruby
services:
  - docker

before_install:
  - docker pull coedl/elpis:interspeech-19

script:
  - docker run --rm --entrypoint='' coedl/elpis:interspeech-19 sh -c "ls /;git pull origin cnc; git checkout -b cnc; sh /workspaces/elpis/test.sh; pwd; ls; echo 'Now installing things'; pip install coveralls pytest-cov; py.test -v --cov=elpis --cov-report=term-missing; export RESULT=\$?; export GIT_BRANCH=cnc; export COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN; coveralls; exit \$RESULT"

